### ISSUE TITLE
ISSM metric does not work

### ISSUE THREAD

**Issue by mamunTomal** [up42/image-similarity-measures#34] opened 2021-10-27 07:57 UTC
The following error shows up and returns ISSM=0

site-packages/image_similarity_measures/quality_metrics.py:146:
RuntimeWarning: divide by zero encountered in log2
  return -np.sum(np.nan_to_num(H * np.log2(H)))

**Comment by chrieke** [comment] 2021-12-02 01:28
Hi @mamunTomal, thanks for reporting. I can reproduce the RuntimeWarning, however the evaluation metric is still correctly reported. Could you give more detail on how you are using the package?

- Python version?
- Via CLI or in Python code?
- Is this the full error message?
- Which image array size, maybe you could even upload the images somewhere so that I can recreate?

**Comment by Safiullahmarwat** [comment] 2021-12-04 07:33
Hi @chrieke the same error I am receiving. 
```
D:\quality_metrics.py:160: RuntimeWarning: divide by zero encountered in log2
  return -np.sum(np.nan_to_num(H * np.log2(H)))
D:\quality_metrics.py:160: RuntimeWarning: invalid value encountered in multiply
  return -np.sum(np.nan_to_num(H * np.log2(H)))
D:\quality_metrics.py:177: RuntimeWarning: invalid value encountered in double_scalars
  return numerator / denominator
Out[9]: 0.0 
```
I printed H matrix, and it is a 10x10 matrix with some zero elements. 
My python version is 3.7, using via import, and the error occurs for every test images.

**Comment by mamunTomal** [comment] 2021-12-04 07:50
Hi @chrieke I received the same error as shown by @Safiullahmarwat. I used python 3.6 and 3.7 in different environments. I later resorted to write my own code in Matlab and got the results from there. I plan to share the matlab implementation of ISSM once I am sure it is bug free.

**Comment by Safiullahmarwat** [comment] 2021-12-04 08:30
@mamunTomal can you please share the values you used for thresholds? as in this code 
```
g = cv2.Canny((x* 0.0625).astype(np.uint8), 100, 200)
h = cv2.Canny((y* 0.0625).astype(np.uint8), 100, 200)
```
here g and h, both are zero valued. I think this is the issue.

**Comment by nikooc2s** [comment] 2021-12-07 23:14
I am happy that it is resolved. We need to be more clear that we first implemented this library considering satellite images with physical values (e.g. surface or top-of-the-atmosphere products with some sort of corrections) for each pixel which can be captured with 12bits numbers. (Note that the end product is in 16bit because computers are optimized to deal with 8, 16, or 32 bit numbers).

**Comment by nikooc2s** [comment] 2021-12-07 23:15
@chrieke Also this one, can you close it. Thanks!

**Closed** 2022-01-11 15:51 UTC
